---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: drupal
  namespace: drupal-ns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: drupal.taungtechnology.co.za
    http:
      paths:
      - backend:
          serviceName: drupal
          servicePort: 80
